# Generated by Django 2.0.6 on 2018-09-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raw_file', models.FileField(upload_to='')),
                ('remark', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
