# Generated by Django 2.0.6 on 2018-09-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_audio_denoised'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='transformed',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
